GET http://localhost:2500/students

###
POST http://localhost:2500/students
Content-Type : application/json

{
    "name" : "name"
}
###
PUT http://localhost:2500/students
Content-Type: application/json

{
    "name" : "name"
}

###
DELETE http://localhost:2500/students

###
GET http://localhost:2500/mvc

###
POST http://localhost:2500/mvc
Content-Type: application/json

{
    "name" : "name"
}